apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app2
  template:
    metadata:
      labels:
        app: my-node-app2
    spec:
      containers:
        - name: my-node-app2
          image: my-node-app2:latest
          ports:
            - containerPort: 3000
